admin_homepage:
    path:     /
    defaults: { _controller: adminBundle:Default:index }
#admin_login_check:
 #   path:     /login
  #  defaults: { _controller: adminBundle:Default:login }
   # methods:  POST
admin_area:
    path:     /welcome
    defaults: { _controller: adminBundle:adminArea:index }
cat_Manager:
    path: /Categories/Manager
    defaults: { _controller: adminBundle:categories:index }

cat_add:
    path: /Categories/Ajout
    defaults: { _controller: adminBundle:categories:add }
cat_create:
    path: /addCat
    methods: POST
    defaults: { _controller: adminBundle:categories:createCat }
cat_edit:
    path: /Categorie/{id}/edit
    defaults: { _controller: adminBundle:categories:editCat }
cat_submit_edit:
    path: /Categories/{id}/edit
    defaults: { _controller: adminBundle:categories:edit }
    methods: POST
change_Cat:
    path: /Categories/{id}/change
    defaults: { _controller: adminBundle:categories:changeStatus}