<?php

namespace adminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * adminUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adminUsersRepository extends EntityRepository
{
}
